services:
  mongo:
    image: mongo:8
    ports:
      - 27017:27017
    env_file:
      - ../.env
    volumes:
      - mongo_data:/data/db

  # postgres:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: base
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - pg_data:/var/lib/postgresql/data

  server:
    build:
      context: ../
      dockerfile: docker/dev/Dockerfile.server
    image: base-server-dev:latest
    env_file:
      - ../.env
    ports:
      - 3000:3000
    depends_on:
      - mongo
      #- postgres
    volumes:
      - ../packages/server:/app/packages/server
      - ../packages/shared:/app/packages/server/node_modules/@base/shared
    command: sh -c "pnpm install && npx prisma generate && npx prisma db push && pnpm start:dev"

  client:
    build:
      context: ../
      dockerfile: docker/dev/Dockerfile.client
    image: base-client-dev:latest
    env_file:
      - ../.env
    ports:
      - 5173:5173
    depends_on:
      - server
    volumes:
      - ../packages/client:/app/packages/client
      - ../packages/shared:/app/packages/client/node_modules/@base/shared
    command: sh -c "pnpm install && pnpm dev"

volumes:
  mongo_data:
  #pg_data:
  server_node_modules:
  client_node_modules:
