services:
  postgres:
    image: postgres:15
    env_file:
      - ../.env
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

  server:
    build:
      context: ../
      dockerfile: docker/prod/Dockerfile.server
    image: base-server-prod:latest
    env_file:
      - ../.env
    ports:
      - 3000:3000
    depends_on:
      - postgres

  client:
    build:
      context: ..
      dockerfile: docker/prod/Dockerfile.client
    image: base-client-prod:latest
    env_file:
      - ../.env
    ports:
      - 80:80
    depends_on:
      - server

volumes:
  pg_data:
