FROM node:20-alpine as builder
WORKDIR /app
COPY ../../packages/client/package*.json ./
RUN npm install -g pnpm && pnpm install
COPY ../../packages/client .
RUN pnpm build

FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
